apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2021-11-06T00:00:07Z"
  labels:
    created-by: image-pruner
  managedFields:
  - apiVersion: batch/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:created-by: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"12d0a402-ba67-4dcc-9922-cff7f2de33b2"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:backoffLimit: {}
        f:completions: {}
        f:parallelism: {}
        f:template:
          f:spec:
            f:affinity: {}
            f:containers:
              k:{"name":"image-pruner"}:
                .: {}
                f:args: {}
                f:command: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources:
                  .: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/var/run/configmaps/serviceca"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"serviceca"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:name: {}
                f:name: {}
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Failed"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:failed: {}
        f:startTime: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-11-06T00:00:24Z"
  name: image-pruner-1636156800
  namespace: openshift-image-registry
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: image-pruner
    uid: 12d0a402-ba67-4dcc-9922-cff7f2de33b2
  resourceVersion: "4779218"
  selfLink: /apis/batch/v1/namespaces/openshift-image-registry/jobs/image-pruner-1636156800
  uid: 695031a3-85e4-4e96-80ce-28e073f4cc46
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 695031a3-85e4-4e96-80ce-28e073f4cc46
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 695031a3-85e4-4e96-80ce-28e073f4cc46
        job-name: image-pruner-1636156800
    spec:
      affinity: {}
      containers:
      - args:
        - adm
        - prune
        - images
        - --confirm=true
        - --certificate-authority=/var/run/configmaps/serviceca/service-ca.crt
        - --keep-tag-revisions=3
        - --keep-younger-than=60m
        - --ignore-invalid-refs=true
        - --loglevel=1
        - --prune-registry=true
        - --registry-url=https://image-registry.openshift-image-registry.svc:5000
        command:
        - oc
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:61ef507064b56a3b9efb10b668a9ad45840ea85200e496401f1e39b7d6b8331b
        imagePullPolicy: IfNotPresent
        name: image-pruner
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/run/configmaps/serviceca
          name: serviceca
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: pruner
      serviceAccountName: pruner
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: serviceca
        name: serviceca
status:
  conditions:
  - lastProbeTime: "2021-11-06T00:00:24Z"
    lastTransitionTime: "2021-11-06T00:00:24Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 1
  startTime: "2021-11-06T00:00:07Z"
