apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1","meta.helm.sh/release-name":"ocp-core-dev-mdb001-mongodb","meta.helm.sh/release-namespace":"iap-core-dev"},"creationTimestamp":"2021-09-13T06:18:39Z","generation":3,"labels":{"app":"mongodb","app.kubernetes.io/managed-by":"Helm","chart":"mongodb-7.8.8","heritage":"Helm","release":"ocp-core-dev-mdb001-mongodb"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:deployment.kubernetes.io/revision":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{}},"f:labels":{".":{},"f:app":{},"f:app.kubernetes.io/managed-by":{},"f:chart":{},"f:heritage":{},"f:release":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:app":{},"f:release":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:app":{},"f:chart":{},"f:release":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"ocp-core-dev-mdb001-mongodb\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"MONGODB_DATABASE\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MONGODB_DISABLE_SYSTEM_LOG\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MONGODB_ENABLE_DIRECTORY_PER_DB\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MONGODB_ENABLE_IPV6\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MONGODB_PASSWORD\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"MONGODB_ROOT_PASSWORD\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"MONGODB_SYSTEM_LOG_VERBOSITY\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MONGODB_USERNAME\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:livenessProbe":{".":{},"f:exec":{".":{},"f:command":{}},"f:failureThreshold":{},"f:initialDelaySeconds":{},"f:periodSeconds":{},"f:successThreshold":{},"f:timeoutSeconds":{}},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":27017,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:name":{},"f:protocol":{}}},"f:readinessProbe":{".":{},"f:exec":{".":{},"f:command":{}},"f:failureThreshold":{},"f:initialDelaySeconds":{},"f:periodSeconds":{},"f:successThreshold":{},"f:timeoutSeconds":{}},"f:resources":{},"f:securityContext":{".":{},"f:runAsNonRoot":{},"f:runAsUser":{}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/bitnami/mongodb\"}":{".":{},"f:mountPath":{},"f:name":{}}}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{".":{},"f:fsGroup":{}},"f:terminationGracePeriodSeconds":{},"f:volumes":{".":{},"k:{\"name\":\"data\"}":{".":{},"f:name":{},"f:persistentVolumeClaim":{".":{},"f:claimName":{}}}}}}}},"manager":"oc","operation":"Update","time":"2021-09-13T06:18:39Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:replicas":{},"f:unavailableReplicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2021-09-13T15:24:22Z"}],"name":"ocp-core-dev-mdb001-mongodb","namespace":"iap-core-dev","resourceVersion":"9026042","selfLink":"/apis/apps/v1/namespaces/iap-core-dev/deployments/ocp-core-dev-mdb001-mongodb","uid":"f6b48b8b-49ae-4257-a3a5-effc6543a41f"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"mongodb","release":"ocp-core-dev-mdb001-mongodb"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"mongodb","chart":"mongodb-7.8.8","release":"ocp-core-dev-mdb001-mongodb"}},"spec":{"containers":[{"env":[{"name":"MONGODB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"mongodb-password","name":"ocp-core-dev-mdb001-mongodb"}}},{"name":"MONGODB_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"mongodb-root-password","name":"ocp-core-dev-mdb001-mongodb"}}},{"name":"MONGODB_USERNAME","value":"boomerang"},{"name":"MONGODB_SYSTEM_LOG_VERBOSITY","value":"0"},{"name":"MONGODB_DISABLE_SYSTEM_LOG","value":"no"},{"name":"MONGODB_DATABASE","value":"boomerang"},{"name":"MONGODB_ENABLE_IPV6","value":"no"},{"name":"MONGODB_ENABLE_DIRECTORY_PER_DB","value":"no"}],"image":"docker.io/bitnami/mongodb:4.2.5","imagePullPolicy":"IfNotPresent","livenessProbe":{"exec":{"command":["mongo","--eval","db.adminCommand('ping')"]},"failureThreshold":6,"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"ocp-core-dev-mdb001-mongodb","ports":[{"containerPort":27017,"name":"mongodb","protocol":"TCP"}],"readinessProbe":{"exec":{"command":["mongo","--eval","db.adminCommand('ping')"]},"failureThreshold":6,"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{},"securityContext":{"runAsNonRoot":true,"runAsUser":1001},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/bitnami/mongodb","name":"data"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":1001},"terminationGracePeriodSeconds":30,"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"ocp-core-dev-mdb001-mongodb"}}]}}},"status":{"conditions":[{"lastTransitionTime":"2021-09-13T08:01:00Z","lastUpdateTime":"2021-09-13T08:01:00Z","message":"ReplicaSet \"ocp-core-dev-mdb001-mongodb-5f4f77559f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2021-09-13T15:24:22Z","lastUpdateTime":"2021-09-13T15:24:22Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"}],"observedGeneration":3,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
    meta.helm.sh/release-name: ocp-core-dev-mdb001-mongodb
    meta.helm.sh/release-namespace: iap-core-dev
  creationTimestamp: "2021-09-13T15:29:22Z"
  generation: 1
  labels:
    app: mongodb
    app.kubernetes.io/managed-by: Helm
    chart: mongodb-7.8.8
    heritage: Helm
    release: ocp-core-dev-mdb001-mongodb
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
            f:release: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:chart: {}
              f:release: {}
          f:spec:
            f:containers:
              k:{"name":"ocp-core-dev-mdb001-mongodb"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"MONGODB_DATABASE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONGODB_DISABLE_SYSTEM_LOG"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONGODB_ENABLE_DIRECTORY_PER_DB"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONGODB_ENABLE_IPV6"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONGODB_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"MONGODB_ROOT_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"MONGODB_SYSTEM_LOG_VERBOSITY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONGODB_USERNAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:livenessProbe:
                  .: {}
                  f:exec:
                    .: {}
                    f:command: {}
                  f:failureThreshold: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":27017,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:exec:
                    .: {}
                    f:command: {}
                  f:failureThreshold: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:resources: {}
                f:securityContext:
                  .: {}
                  f:runAsNonRoot: {}
                  f:runAsUser: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/bitnami/mongodb"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext:
              .: {}
              f:fsGroup: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"data"}:
                .: {}
                f:name: {}
                f:persistentVolumeClaim:
                  .: {}
                  f:claimName: {}
    manager: oc
    operation: Update
    time: "2021-09-13T15:29:22Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:replicas: {}
        f:unavailableReplicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-09-14T03:49:59Z"
  name: ocp-core-dev-mdb001-mongodb
  namespace: iap-core-dev
  resourceVersion: "10555990"
  selfLink: /apis/apps/v1/namespaces/iap-core-dev/deployments/ocp-core-dev-mdb001-mongodb
  uid: 9ebcca07-1964-486c-b2d2-a816d3ced621
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongodb
      release: ocp-core-dev-mdb001-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
        chart: mongodb-7.8.8
        release: ocp-core-dev-mdb001-mongodb
    spec:
      containers:
      - env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-password
              name: ocp-core-dev-mdb001-mongodb
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: ocp-core-dev-mdb001-mongodb
        - name: MONGODB_USERNAME
          value: boomerang
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_DATABASE
          value: boomerang
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        image: docker.io/bitnami/mongodb:4.2.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: ocp-core-dev-mdb001-mongodb
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ocp-core-dev-mdb001-mongodb
status:
  conditions:
  - lastTransitionTime: "2021-09-13T15:29:22Z"
    lastUpdateTime: "2021-09-13T15:29:22Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2021-09-14T03:49:59Z"
    lastUpdateTime: "2021-09-14T03:49:59Z"
    message: ReplicaSet "ocp-core-dev-mdb001-mongodb-5f4f77559f" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
