apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheus:
      retention: 96h
      resources:
        requests:
          cpu: 200m 
          memory: 500Mi
      volumeClaimTemplate:
        spec:
          storageClassName: ibmc-block-silver
          resources:
            requests:
              storage: 100Gi