COMPUTED VALUES:
USER-SUPPLIED VALUES: null
affinity: {}
apps:
  admin:
    image:
      repository: /core-app-admin
      tag: 5.6.168-845
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  catalog:
    image:
      repository: /core-app-catalog
      tag: 1.6.32-215
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  content:
    image:
      repository: /core-app-welcome
      tag: 0.1.14-34
    replicaCount: 0
    service:
      type: ClusterIP
    zone: untrusted
  docs:
    image:
      repository: /core-app-docs
      tag: 1.12.19-366
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  launchpad:
    image:
      repository: /core-app-launchpad
      tag: 5.5.153-754
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  status:
    image:
      repository: /core-app-status
      tag: 5.3.41-142
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
auth:
  enabled: true
  mode: oauth
  namespace: iap-core-uat
  prefix: /oauth
  serviceName: iap-auth-proxy
  signOutRedirect: https%3A%2F%2Fpreprod.login.w3.ibm.com%2Fpkmslogout
bmrgcommon:
  global: {}
clients:
  apis:
    image:
      repository: /core-client-apis
      tag: 0.0.66-60
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
core:
  platform:
    name: Essentials Core
    version: 7.6.0
database:
  mongodb:
    adminPassword: null
    host: ocp-core-uat-mdb001-mongodb
    password: passw0rd
    port: 27017
    secretName: ocp-core-uat-mdb001-mongodb
    user: boomerang
general:
  enable:
    apis: false
    debug: false
    docs: false
    metering: true
    notifications: true
    support: false
    welcome: false
  namePrefix: iap-core
hostAliases:
- hostnames:
  - faces.tap.ibm.com
  - w3-services1.w3-969.ibm.com
  ip: 9.220.2.10
image:
  pullPolicy: IfNotPresent
  pullSecret: ocp.registrykey
  registry: us.icr.io/boomerang-lib-docker-external/ise
ingress:
  annotationsPrefix: ingress.kubernetes.io
  class: nginx
  enabled: true
  host: uat-cluster-9fb7e40700ceec3a76e70fdb30f06230-0000.eu-de.containers.appdomain.cloud
  launchpadAppRoot: false
  root: /uat
  singleIngressFile: false
  tlsSecretName: ocp-tls-cloud-uat
job:
  data:
    enabled: true
    image:
      repository: /core-loader
      tag: 0.3.46-81
    profile: core
ldap:
  base: dc=boomerangplatform,dc=net
  password: passw0rd
  port: 389
  user: cn=Directory Manager
  userPassword: passw0rd
monitoring:
  contrast:
    api:
      key: null
      proxy:
        scheme: http
      service:
        key: null
      url: https://app.contrastsecurity.com/Contrast
      username: null
    enable: false
    image:
      registry: boomerangio
      repository: /util-contrastjavaagent
      tag: 3.8.0.18219
    server:
      environment: development
      name: ServerName
  jaeger:
    agent:
      host: jaeger-uat-agent
      port: 6831
    collector:
      host: jaeger-uat-collector
      port: 14268
    enabled: true
    namespace: jaeger-uat
    remoteControlledSampler:
      host: jaeger-uat-agent
      port: 5778
  newrelic:
    apm:
      image:
        registry: boomerangio
        repository: /util-newrelicjavaagent
        tag: 5.14.0
      key: null
      name: Boomerang Private
    browser:
      id: null
      key: null
nodeSelector: {}
opa:
  enabled: false
  image:
    repository: openpolicyagent/opa
    tag: 0.13.5
  replicaCount: 0
  service:
    type: ClusterIP
proxy:
  enable: false
services:
  admin:
    image:
      repository: /core-service-admin
      tag: 8.6.154-958
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  audit:
    image:
      repository: /core-service-audit
      tag: 1.2.33-59
    replicaCount: 1
    service:
      type: ClusterIP
    zone: semi-trusted
  auth:
    image:
      repository: /core-service-auth
      tag: 6.2.45-118
    replicaCount: 1
    service:
      type: ClusterIP
    zone: semi-trusted
  controller:
    image:
      repository: /core-service-controller
      tag: 0.2.1-38
    replicaCount: 0
    securityPolicy: ibm-privileged-psp
    service:
      type: ClusterIP
    zone: semi-trusted
  launchpad:
    image:
      repository: /core-service-launchpad
      tag: 6.3.225-573
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  messaging:
    image:
      repository: /core-service-messaging
      tag: 0.1.73-90
    replicaCount: 1
    service:
      type: ClusterIP
    zone: semi-trusted
  metering:
    image:
      repository: /core-service-metering
      tag: 0.1.19-30
    replicaCount: 1
    service:
      type: ClusterIP
    zone: semi-trusted
  notifications:
    image:
      repository: /core-service-notifications
      tag: 1.3.10-79
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  settings:
    image:
      repository: /core-service-settings
      tag: 0.1.4-45
    replicaCount: 1
    service:
      type: ClusterIP
    zone: semi-trusted
  status:
    image:
      repository: /core-service-status
      tag: 5.2.78-153
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  support:
    image:
      repository: /core-service-support
      tag: 6.4.195-203
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  users:
    image:
      repository: /core-service-users
      tag: 1.2.64-156
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
tolerations: []
wordpress:
  url: null
