apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      retention: 96h
      volumeClaimTemplate:
        spec:
          storageClassName: ibmc-block-silver
          resources:
            requests:
              storage: 40Gi